### PR TITLE
add option "win" for specifion non-current window

### PR DESCRIPTION
**Pull request by examan**
use case: when using favico.js iframe, set win to top.

### CODE REVIEW

**Comment by ejci** [comment]
Im not sure if I understand the use case. You are trying to change the parent window favicon from iFrame? Isnt it better to have favico.js in parent window and if needed call setBadge method from iFrame?

**Comment by examan** [comment]
In my project, the main page may or may not be in an frame wrapper, so I need to specify the top window for both cases.

**Comment by ejci** [comment]
merged. I will release a new version shortly

**Comment by examan** [comment]
thx a lot :)

**Pull request merged**
