### PR TITLE
Added `setter` support. Fixes #54

### LINKED ISSUE #54: Allow for dynamic setter function
I am interested in using `favico.js` for `slack-for-linux` to indicate unseen notifications. It would be used in the tray icon and possibly taskbar icon. Currently `favico.js` doesn't support this because it can only set against `elementId` or a `<link>` it creates.

To support this functionality, I suggest adding a new option which is a `setter` callback (i.e. a function that is run every time the image changes). With an integration into `node-webkit`, it would look like:

```js
var favicon = new Favico({
  setter: function (png) {
    tray.icon = png;
  }
});
```

### PR DESCRIPTION
**Pull request by twolfson**
As discusssed in #54, we need some way of adding custom header support. In this PR:

- Added support for `_opt.setter` to push updates to custom item

### CODE REVIEW

**Comment by twolfson** [comment]
Sweet, thanks for landing this =) Any idea when the next release is going to be?

**Comment by ejci** [comment]
I hope IN 1-2 weeks. I dont want to promise exact date as Im a little bit busy... but I will try to do ASAP.

**Comment by twolfson** [comment]
It's been 2 weeks. Any chance of a release?

**Comment by ejci** [comment]
0.3.7 was shipped. Sorry for the delay.

**Comment by twolfson** [comment]
Cool, everything seems to work with the changes. Thanks!

**Pull request merged**
