### PR TITLE
Update all linked icons

### PR DESCRIPTION
**Pull request by ubershmekel**
This fixes the chrome issue
https://github.com/ejci/favico.js/issues/85

### CODE REVIEW

**Comment by sebastienbarre** [comment]
This is fixing this issue nicely for Chrome, +1 to merge and release 0.3.11 :)

**Comment by djbuch** [comment]
+1 for merge also this works in Chrome !

**Comment by sebastienbarre** [comment]
Would definitely recommend merging.

**Comment by ubershmekel** [comment]
@ejci do you have time in the next 6 months to evaluate or merge pull requests?

**Comment by seiyria** [comment]
This definitely works rather well. For the time being I'm working off of @ubershmekel's patch but I'd rather this be upstream. @ejci do you need help maintaining this?

**Pull request merged**
